var Handlebars = require("handlebars");
var pdf = require("html-pdf");

/**
 * pdf generator
 */
export class PDFMaster {


  static async create(document: any, options: any): Promise<any> {
    return new Promise((resolve, reject) => {
      if (!document || !document.html || !document.data) {
        reject(new Error("Some, or all, options are missing."));
      }
      // Compiles a template
      var html = Handlebars.compile(document.html)(document.data);
      var pdfPromise = pdf.create(html, options);
      // Create PDF from html template generated by handlebars
      // Output will be PDF file
      switch (document.type) {
        case "buffer":
          pdfPromise.toBuffer((err: Error, res: any) => {
            if (!err) resolve(res);
            else reject(err);
          });
          break;

        case "stream":
          pdfPromise.toStream((err: Error, res: any) => {
            if (!err) resolve(res);
            else reject(err);
          });
          break;

        default:
          pdfPromise.toFile(document.path, (err: Error, res: any) => {
            if (!err) resolve(res);
            else reject(err);
          });
          break;
      }
    });
  }
}